name: party360
description: "Camara 360."
publish_to: 'none'

version: 1.0.0+19

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  video_player: ^2.8.1
  path_provider: ^2.1.1
  path: ^1.8.3
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.5
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/ 
